import "../styles/globals.css";
import Header from "../components/utilities/Header";
import { usePathname } from "next/navigation";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {usePathname === "/" && <title>Simon Beirouti | Home</title>}
        {usePathname === "/posts" && <title>Simon Beirouti | Posts</title>}
        {usePathname === "/projects" && (
          <title>Simon Beirouti | Projects</title>
        )}
        {usePathname === "/experiences" && (
          <title>Simon Beirouti | Experiences</title>
        )}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
